/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 1
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_type = 2,
  anon_sym_generic = 3,
  anon_sym_scope = 4,
  anon_sym_define = 5,
  anon_sym_match = 6,
  anon_sym_fn = 7,
  anon_sym_module = 8,
  aux_sym_ark_definition_token1 = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  anon_sym_SQUOTE = 13,
  anon_sym_DQUOTE = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  anon_sym_COLON = 17,
  anon_sym_PIPE = 18,
  anon_sym_LBRACK_RBRACK = 19,
  anon_sym_LBRACK = 20,
  anon_sym_RBRACK = 21,
  anon_sym_string = 22,
  anon_sym_number = 23,
  anon_sym_boolean = 24,
  anon_sym_bigint = 25,
  anon_sym_symbol = 26,
  anon_sym_unknown = 27,
  anon_sym_any = 28,
  anon_sym_never = 29,
  anon_sym_void = 30,
  anon_sym_LT = 31,
  anon_sym_GT = 32,
  anon_sym_EQ = 33,
  anon_sym_PERCENT = 34,
  anon_sym_AMP = 35,
  sym_unescaped_double_string_fragment = 36,
  sym_unescaped_single_string_fragment = 37,
  anon_sym_DASH = 38,
  anon_sym_PLUS = 39,
  sym_number = 40,
  sym_true = 41,
  sym_false = 42,
  sym_null = 43,
  sym_undefined = 44,
  sym_optional = 45,
  sym_source_file = 46,
  sym_ark_definition = 47,
  sym_type_definition = 48,
  sym__type_expression = 49,
  sym_object_type = 50,
  sym_ark_property_signature = 51,
  sym_ark_expression = 52,
  sym_union_type = 53,
  sym_array_type = 54,
  sym_tuple_type = 55,
  sym_parenthesized_type = 56,
  sym_literal_type = 57,
  sym_primitive_type = 58,
  sym_ark_operator = 59,
  sym__property_name = 60,
  sym__required_property_name = 61,
  sym__optional_property_name = 62,
  sym_computed_property_name = 63,
  sym__number = 64,
  aux_sym_ark_definition_repeat1 = 65,
  aux_sym_object_type_repeat1 = 66,
  aux_sym_ark_double_string_repeat1 = 67,
  aux_sym_ark_single_string_repeat1 = 68,
  alias_sym_property_identifier = 69,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_type] = "ark_keyword",
  [anon_sym_generic] = "ark_keyword",
  [anon_sym_scope] = "ark_keyword",
  [anon_sym_define] = "ark_keyword",
  [anon_sym_match] = "ark_keyword",
  [anon_sym_fn] = "ark_keyword",
  [anon_sym_module] = "ark_keyword",
  [aux_sym_ark_definition_token1] = "ark_keyword",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_string] = "string",
  [anon_sym_number] = "number",
  [anon_sym_boolean] = "boolean",
  [anon_sym_bigint] = "bigint",
  [anon_sym_symbol] = "symbol",
  [anon_sym_unknown] = "unknown",
  [anon_sym_any] = "any",
  [anon_sym_never] = "never",
  [anon_sym_void] = "void",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_PERCENT] = "%",
  [anon_sym_AMP] = "&",
  [sym_unescaped_double_string_fragment] = "string_fragment",
  [sym_unescaped_single_string_fragment] = "string_fragment",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [sym_number] = "number",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_undefined] = "undefined",
  [sym_optional] = "optional",
  [sym_source_file] = "source_file",
  [sym_ark_definition] = "ark_definition",
  [sym_type_definition] = "type_definition",
  [sym__type_expression] = "_type_expression",
  [sym_object_type] = "object_type",
  [sym_ark_property_signature] = "ark_property_signature",
  [sym_ark_expression] = "ark_expression",
  [sym_union_type] = "union_type",
  [sym_array_type] = "array_type",
  [sym_tuple_type] = "tuple_type",
  [sym_parenthesized_type] = "parenthesized_type",
  [sym_literal_type] = "literal_type",
  [sym_primitive_type] = "primitive_type",
  [sym_ark_operator] = "ark_operator",
  [sym__property_name] = "_property_name",
  [sym__required_property_name] = "_required_property_name",
  [sym__optional_property_name] = "_optional_property_name",
  [sym_computed_property_name] = "computed_property_name",
  [sym__number] = "unary_expression",
  [aux_sym_ark_definition_repeat1] = "ark_definition_repeat1",
  [aux_sym_object_type_repeat1] = "object_type_repeat1",
  [aux_sym_ark_double_string_repeat1] = "ark_double_string_repeat1",
  [aux_sym_ark_single_string_repeat1] = "ark_single_string_repeat1",
  [alias_sym_property_identifier] = "property_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_generic] = anon_sym_type,
  [anon_sym_scope] = anon_sym_type,
  [anon_sym_define] = anon_sym_type,
  [anon_sym_match] = anon_sym_type,
  [anon_sym_fn] = anon_sym_type,
  [anon_sym_module] = anon_sym_type,
  [aux_sym_ark_definition_token1] = anon_sym_type,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_bigint] = anon_sym_bigint,
  [anon_sym_symbol] = anon_sym_symbol,
  [anon_sym_unknown] = anon_sym_unknown,
  [anon_sym_any] = anon_sym_any,
  [anon_sym_never] = anon_sym_never,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_unescaped_double_string_fragment] = sym_unescaped_double_string_fragment,
  [sym_unescaped_single_string_fragment] = sym_unescaped_double_string_fragment,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_number] = sym_number,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_undefined] = sym_undefined,
  [sym_optional] = sym_optional,
  [sym_source_file] = sym_source_file,
  [sym_ark_definition] = sym_ark_definition,
  [sym_type_definition] = sym_type_definition,
  [sym__type_expression] = sym__type_expression,
  [sym_object_type] = sym_object_type,
  [sym_ark_property_signature] = sym_ark_property_signature,
  [sym_ark_expression] = sym_ark_expression,
  [sym_union_type] = sym_union_type,
  [sym_array_type] = sym_array_type,
  [sym_tuple_type] = sym_tuple_type,
  [sym_parenthesized_type] = sym_parenthesized_type,
  [sym_literal_type] = sym_literal_type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_ark_operator] = sym_ark_operator,
  [sym__property_name] = sym__property_name,
  [sym__required_property_name] = sym__required_property_name,
  [sym__optional_property_name] = sym__optional_property_name,
  [sym_computed_property_name] = sym_computed_property_name,
  [sym__number] = sym__number,
  [aux_sym_ark_definition_repeat1] = aux_sym_ark_definition_repeat1,
  [aux_sym_object_type_repeat1] = aux_sym_object_type_repeat1,
  [aux_sym_ark_double_string_repeat1] = aux_sym_ark_double_string_repeat1,
  [aux_sym_ark_single_string_repeat1] = aux_sym_ark_single_string_repeat1,
  [alias_sym_property_identifier] = alias_sym_property_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_generic] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_scope] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_ark_definition_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bigint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_symbol] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unknown] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_never] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_unescaped_double_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_unescaped_single_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_undefined] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_ark_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__type_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_object_type] = {
    .visible = true,
    .named = true,
  },
  [sym_ark_property_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_ark_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_union_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_type] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_ark_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__property_name] = {
    .visible = false,
    .named = true,
  },
  [sym__required_property_name] = {
    .visible = false,
    .named = true,
  },
  [sym__optional_property_name] = {
    .visible = false,
    .named = true,
  },
  [sym_computed_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym__number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_ark_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ark_double_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ark_single_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_property_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_element = 2,
  field_left = 3,
  field_name = 4,
  field_operator = 5,
  field_right = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_element] = "element",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 0, .inherited = true},
    {field_operator, 0, .inherited = true},
  [2] =
    {field_argument, 1},
    {field_operator, 0},
  [4] =
    {field_element, 0},
  [5] =
    {field_left, 0},
    {field_right, 2},
  [7] =
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = alias_sym_property_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 23,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 28,
  [33] = 29,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 26,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 92,
  [94] = 94,
  [95] = 83,
  [96] = 96,
};

static const TSCharacterRange sym_identifier_character_set_2[] = {
  {'$', '$'}, {'0', '9'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'}, {'a', 'z'}, {0x7f, 0x9f}, {0xa1, 0x167f},
  {0x1681, 0x1fff}, {0x200c, 0x2027}, {0x202a, 0x202e}, {0x2030, 0x205e}, {0x2061, 0x2fff}, {0x3001, 0xfefe}, {0xff00, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 27,
        '%', 38,
        '&', 39,
        '\'', 26,
        '(', 23,
        ')', 25,
        '+', 46,
        ',', 24,
        '-', 45,
        '.', 13,
        '0', 48,
        ':', 30,
        '<', 35,
        '=', 37,
        '>', 36,
        '?', 57,
        '[', 33,
        '\\', 6,
        ']', 34,
        '{', 28,
        '|', 31,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (set_contains(sym_identifier_character_set_2, 15, lookahead)) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '{') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 10:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(51);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(52);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 27,
        '%', 38,
        '&', 39,
        '\'', 26,
        ')', 25,
        ',', 24,
        '<', 35,
        '=', 37,
        '>', 36,
        '[', 5,
        ']', 34,
        '|', 31,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(6);
      if (set_contains(sym_identifier_character_set_2, 15, lookahead)) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_unescaped_single_string_fragment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_unescaped_single_string_fragment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 56,
        '0', 54,
        '_', 14,
        'n', 47,
        'B', 10,
        'b', 10,
        'E', 9,
        'e', 9,
        'O', 11,
        'o', 11,
        'X', 17,
        'x', 17,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(47);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_optional);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'A', 1,
        'a', 2,
        'b', 3,
        'd', 4,
        'f', 5,
        'g', 6,
        'm', 7,
        'n', 8,
        's', 9,
        't', 10,
        'u', 11,
        'v', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 't') ADVANCE(26);
      if (lookahead == 'y') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(28);
      if (lookahead == 'y') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 'k') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'y') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(36);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 23:
      if (lookahead == 'v') ADVANCE(41);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(42);
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(46);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead == 'k') ADVANCE(50);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_ark_definition_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_any);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(57);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(58);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 43:
      if (lookahead == 'b') ADVANCE(61);
      END_STATE();
    case 44:
      if (lookahead == 'p') ADVANCE(62);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 46:
      if (lookahead == 'b') ADVANCE(64);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 51:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(70);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(72);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 57:
      if (lookahead == 'h') ADVANCE(75);
      END_STATE();
    case 58:
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 67:
      if (lookahead == 'f') ADVANCE(82);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 71:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_never);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(89);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_scope);
      END_STATE();
    case 80:
      if (lookahead == 'g') ADVANCE(90);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(91);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(92);
      END_STATE();
    case 83:
      if (lookahead == 'w') ADVANCE(93);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_bigint);
      END_STATE();
    case 85:
      if (lookahead == 'n') ADVANCE(94);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 87:
      if (lookahead == 'c') ADVANCE(95);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_symbol);
      END_STATE();
    case 92:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_generic);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_unknown);
      END_STATE();
    case 98:
      if (lookahead == 'd') ADVANCE(99);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_undefined);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 21},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 21},
  [32] = {.lex_state = 21},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 21},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 21},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 21},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 21},
  [43] = {.lex_state = 21},
  [44] = {.lex_state = 21},
  [45] = {.lex_state = 21},
  [46] = {.lex_state = 21},
  [47] = {.lex_state = 21},
  [48] = {.lex_state = 21},
  [49] = {.lex_state = 21},
  [50] = {.lex_state = 21},
  [51] = {.lex_state = 21},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_generic] = ACTIONS(1),
    [anon_sym_scope] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [aux_sym_ark_definition_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_bigint] = ACTIONS(1),
    [anon_sym_symbol] = ACTIONS(1),
    [anon_sym_unknown] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_never] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_undefined] = ACTIONS(1),
    [sym_optional] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(88),
    [sym_ark_definition] = STATE(14),
    [sym_type_definition] = STATE(89),
    [sym_object_type] = STATE(14),
    [sym_tuple_type] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(5),
    [anon_sym_generic] = ACTIONS(5),
    [anon_sym_scope] = ACTIONS(5),
    [anon_sym_define] = ACTIONS(5),
    [anon_sym_match] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(5),
    [anon_sym_module] = ACTIONS(5),
    [aux_sym_ark_definition_token1] = ACTIONS(5),
    [anon_sym_SQUOTE] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      sym__number,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 5,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      sym_undefined,
    STATE(45), 8,
      sym__type_expression,
      sym_ark_expression,
      sym_union_type,
      sym_array_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_literal_type,
      sym_primitive_type,
    ACTIONS(21), 9,
      anon_sym_string,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_bigint,
      anon_sym_symbol,
      anon_sym_unknown,
      anon_sym_any,
      anon_sym_never,
      anon_sym_void,
  [48] = 9,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      sym__number,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 5,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      sym_undefined,
    STATE(50), 8,
      sym__type_expression,
      sym_ark_expression,
      sym_union_type,
      sym_array_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_literal_type,
      sym_primitive_type,
    ACTIONS(21), 9,
      anon_sym_string,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_bigint,
      anon_sym_symbol,
      anon_sym_unknown,
      anon_sym_any,
      anon_sym_never,
      anon_sym_void,
  [96] = 9,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      sym__number,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 5,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      sym_undefined,
    STATE(40), 8,
      sym__type_expression,
      sym_ark_expression,
      sym_union_type,
      sym_array_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_literal_type,
      sym_primitive_type,
    ACTIONS(21), 9,
      anon_sym_string,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_bigint,
      anon_sym_symbol,
      anon_sym_unknown,
      anon_sym_any,
      anon_sym_never,
      anon_sym_void,
  [144] = 9,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      sym__number,
    ACTIONS(23), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 5,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      sym_undefined,
    STATE(38), 8,
      sym__type_expression,
      sym_ark_expression,
      sym_union_type,
      sym_array_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_literal_type,
      sym_primitive_type,
    ACTIONS(21), 9,
      anon_sym_string,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_bigint,
      anon_sym_symbol,
      anon_sym_unknown,
      anon_sym_any,
      anon_sym_never,
      anon_sym_void,
  [192] = 1,
    ACTIONS(27), 20,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_string,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_bigint,
      anon_sym_symbol,
      anon_sym_unknown,
      anon_sym_any,
      anon_sym_never,
      anon_sym_void,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
      sym_undefined,
  [215] = 10,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_COMMA,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      aux_sym_ark_definition_repeat1,
    STATE(92), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [255] = 10,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_COMMA,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(10), 1,
      aux_sym_ark_definition_repeat1,
    STATE(93), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [295] = 10,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_COMMA,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_ark_definition_repeat1,
    STATE(83), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [335] = 10,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_ark_definition_repeat1,
    STATE(95), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [375] = 9,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [412] = 1,
    ACTIONS(43), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [432] = 1,
    ACTIONS(45), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [452] = 1,
    ACTIONS(47), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [472] = 8,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(7), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [506] = 1,
    ACTIONS(53), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [526] = 1,
    ACTIONS(55), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [546] = 8,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [580] = 1,
    ACTIONS(59), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [600] = 1,
    ACTIONS(61), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [620] = 1,
    ACTIONS(63), 17,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [640] = 7,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(84), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [671] = 7,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [702] = 7,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(74), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [733] = 7,
    ACTIONS(7), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 1,
      anon_sym_DQUOTE,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      sym_type_definition,
    STATE(14), 3,
      sym_ark_definition,
      sym_object_type,
      sym_tuple_type,
    ACTIONS(5), 8,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
  [764] = 3,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      aux_sym_ark_definition_repeat1,
    ACTIONS(65), 13,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [786] = 1,
    ACTIONS(65), 15,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [804] = 1,
    ACTIONS(70), 14,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [821] = 1,
    ACTIONS(72), 14,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [838] = 1,
    ACTIONS(74), 14,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [855] = 1,
    ACTIONS(74), 14,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [872] = 1,
    ACTIONS(70), 14,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [889] = 1,
    ACTIONS(72), 14,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [906] = 1,
    ACTIONS(76), 14,
      anon_sym_type,
      anon_sym_generic,
      anon_sym_scope,
      anon_sym_define,
      anon_sym_match,
      anon_sym_fn,
      anon_sym_module,
      aux_sym_ark_definition_token1,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [923] = 1,
    ACTIONS(76), 14,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [940] = 9,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(86), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      sym_number,
    STATE(80), 1,
      sym_ark_property_signature,
    STATE(81), 2,
      sym__required_property_name,
      sym_computed_property_name,
    STATE(91), 2,
      sym__property_name,
      sym__optional_property_name,
  [970] = 9,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(86), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      sym_number,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_ark_property_signature,
    STATE(81), 2,
      sym__required_property_name,
      sym_computed_property_name,
    STATE(91), 2,
      sym__property_name,
      sym__optional_property_name,
  [1000] = 3,
    ACTIONS(94), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(4), 1,
      sym_ark_operator,
    ACTIONS(92), 8,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1017] = 8,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(86), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      sym_number,
    STATE(80), 1,
      sym_ark_property_signature,
    STATE(81), 2,
      sym__required_property_name,
      sym_computed_property_name,
    STATE(91), 2,
      sym__property_name,
      sym__optional_property_name,
  [1044] = 3,
    ACTIONS(94), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(4), 1,
      sym_ark_operator,
    ACTIONS(96), 8,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1061] = 8,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(86), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      sym_number,
    STATE(69), 1,
      sym_ark_property_signature,
    STATE(81), 2,
      sym__required_property_name,
      sym_computed_property_name,
    STATE(91), 2,
      sym__property_name,
      sym__optional_property_name,
  [1088] = 1,
    ACTIONS(98), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1100] = 1,
    ACTIONS(100), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1112] = 1,
    ACTIONS(102), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1124] = 5,
    ACTIONS(94), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(104), 1,
      anon_sym_SQUOTE,
    ACTIONS(106), 1,
      anon_sym_PIPE,
    STATE(4), 1,
      sym_ark_operator,
    ACTIONS(108), 5,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1144] = 1,
    ACTIONS(110), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1156] = 1,
    ACTIONS(112), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1168] = 1,
    ACTIONS(114), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1180] = 1,
    ACTIONS(116), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1192] = 5,
    ACTIONS(94), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(104), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      anon_sym_PIPE,
    STATE(4), 1,
      sym_ark_operator,
    ACTIONS(108), 5,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1212] = 1,
    ACTIONS(118), 9,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PIPE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PERCENT,
      anon_sym_AMP,
  [1224] = 3,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      sym_unescaped_double_string_fragment,
    STATE(64), 1,
      aux_sym_ark_double_string_repeat1,
  [1234] = 3,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
    ACTIONS(126), 1,
      sym_unescaped_double_string_fragment,
    STATE(59), 1,
      aux_sym_ark_double_string_repeat1,
  [1244] = 3,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_ark_definition_repeat1,
  [1254] = 3,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_ark_definition_repeat1,
  [1264] = 3,
    ACTIONS(120), 1,
      anon_sym_SQUOTE,
    ACTIONS(134), 1,
      sym_unescaped_single_string_fragment,
    STATE(61), 1,
      aux_sym_ark_single_string_repeat1,
  [1274] = 3,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_object_type_repeat1,
  [1284] = 3,
    ACTIONS(138), 1,
      anon_sym_SQUOTE,
    ACTIONS(140), 1,
      sym_unescaped_single_string_fragment,
    STATE(58), 1,
      aux_sym_ark_single_string_repeat1,
  [1294] = 3,
    ACTIONS(143), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      sym_unescaped_double_string_fragment,
    STATE(59), 1,
      aux_sym_ark_double_string_repeat1,
  [1304] = 3,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    ACTIONS(150), 1,
      sym_unescaped_single_string_fragment,
    STATE(58), 1,
      aux_sym_ark_single_string_repeat1,
  [1314] = 3,
    ACTIONS(150), 1,
      sym_unescaped_single_string_fragment,
    ACTIONS(152), 1,
      anon_sym_SQUOTE,
    STATE(58), 1,
      aux_sym_ark_single_string_repeat1,
  [1324] = 3,
    ACTIONS(126), 1,
      sym_unescaped_double_string_fragment,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      aux_sym_ark_double_string_repeat1,
  [1334] = 3,
    ACTIONS(154), 1,
      anon_sym_SQUOTE,
    ACTIONS(156), 1,
      sym_unescaped_single_string_fragment,
    STATE(71), 1,
      aux_sym_ark_single_string_repeat1,
  [1344] = 3,
    ACTIONS(126), 1,
      sym_unescaped_double_string_fragment,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      aux_sym_ark_double_string_repeat1,
  [1354] = 3,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_object_type_repeat1,
  [1364] = 3,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
  [1374] = 3,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      sym_unescaped_double_string_fragment,
    STATE(53), 1,
      aux_sym_ark_double_string_repeat1,
  [1384] = 3,
    ACTIONS(171), 1,
      anon_sym_SQUOTE,
    ACTIONS(173), 1,
      sym_unescaped_single_string_fragment,
    STATE(60), 1,
      aux_sym_ark_single_string_repeat1,
  [1394] = 3,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      aux_sym_object_type_repeat1,
  [1404] = 3,
    ACTIONS(171), 1,
      anon_sym_DQUOTE,
    ACTIONS(179), 1,
      sym_unescaped_double_string_fragment,
    STATE(62), 1,
      aux_sym_ark_double_string_repeat1,
  [1414] = 3,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(150), 1,
      sym_unescaped_single_string_fragment,
    STATE(58), 1,
      aux_sym_ark_single_string_repeat1,
  [1424] = 3,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_ark_definition_repeat1,
  [1434] = 1,
    ACTIONS(184), 2,
      anon_sym_COLON,
      sym_optional,
  [1439] = 1,
    ACTIONS(186), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1444] = 1,
    ACTIONS(188), 2,
      anon_sym_COLON,
      sym_optional,
  [1449] = 1,
    ACTIONS(190), 2,
      anon_sym_COLON,
      sym_optional,
  [1454] = 1,
    ACTIONS(192), 2,
      anon_sym_COLON,
      sym_optional,
  [1459] = 1,
    ACTIONS(194), 2,
      anon_sym_COLON,
      sym_optional,
  [1464] = 1,
    ACTIONS(196), 2,
      anon_sym_COLON,
      sym_optional,
  [1469] = 1,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1474] = 2,
    ACTIONS(198), 1,
      anon_sym_COLON,
    ACTIONS(200), 1,
      sym_optional,
  [1481] = 1,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
  [1485] = 1,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
  [1489] = 1,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
  [1493] = 1,
    ACTIONS(208), 1,
      anon_sym_RBRACK,
  [1497] = 1,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
  [1501] = 1,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
  [1505] = 1,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
  [1509] = 1,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
  [1513] = 1,
    ACTIONS(218), 1,
      sym_number,
  [1517] = 1,
    ACTIONS(220), 1,
      anon_sym_COLON,
  [1521] = 1,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
  [1525] = 1,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
  [1529] = 1,
    ACTIONS(222), 1,
      anon_sym_COLON,
  [1533] = 1,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
  [1537] = 1,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 192,
  [SMALL_STATE(7)] = 215,
  [SMALL_STATE(8)] = 255,
  [SMALL_STATE(9)] = 295,
  [SMALL_STATE(10)] = 335,
  [SMALL_STATE(11)] = 375,
  [SMALL_STATE(12)] = 412,
  [SMALL_STATE(13)] = 432,
  [SMALL_STATE(14)] = 452,
  [SMALL_STATE(15)] = 472,
  [SMALL_STATE(16)] = 506,
  [SMALL_STATE(17)] = 526,
  [SMALL_STATE(18)] = 546,
  [SMALL_STATE(19)] = 580,
  [SMALL_STATE(20)] = 600,
  [SMALL_STATE(21)] = 620,
  [SMALL_STATE(22)] = 640,
  [SMALL_STATE(23)] = 671,
  [SMALL_STATE(24)] = 702,
  [SMALL_STATE(25)] = 733,
  [SMALL_STATE(26)] = 764,
  [SMALL_STATE(27)] = 786,
  [SMALL_STATE(28)] = 804,
  [SMALL_STATE(29)] = 821,
  [SMALL_STATE(30)] = 838,
  [SMALL_STATE(31)] = 855,
  [SMALL_STATE(32)] = 872,
  [SMALL_STATE(33)] = 889,
  [SMALL_STATE(34)] = 906,
  [SMALL_STATE(35)] = 923,
  [SMALL_STATE(36)] = 940,
  [SMALL_STATE(37)] = 970,
  [SMALL_STATE(38)] = 1000,
  [SMALL_STATE(39)] = 1017,
  [SMALL_STATE(40)] = 1044,
  [SMALL_STATE(41)] = 1061,
  [SMALL_STATE(42)] = 1088,
  [SMALL_STATE(43)] = 1100,
  [SMALL_STATE(44)] = 1112,
  [SMALL_STATE(45)] = 1124,
  [SMALL_STATE(46)] = 1144,
  [SMALL_STATE(47)] = 1156,
  [SMALL_STATE(48)] = 1168,
  [SMALL_STATE(49)] = 1180,
  [SMALL_STATE(50)] = 1192,
  [SMALL_STATE(51)] = 1212,
  [SMALL_STATE(52)] = 1224,
  [SMALL_STATE(53)] = 1234,
  [SMALL_STATE(54)] = 1244,
  [SMALL_STATE(55)] = 1254,
  [SMALL_STATE(56)] = 1264,
  [SMALL_STATE(57)] = 1274,
  [SMALL_STATE(58)] = 1284,
  [SMALL_STATE(59)] = 1294,
  [SMALL_STATE(60)] = 1304,
  [SMALL_STATE(61)] = 1314,
  [SMALL_STATE(62)] = 1324,
  [SMALL_STATE(63)] = 1334,
  [SMALL_STATE(64)] = 1344,
  [SMALL_STATE(65)] = 1354,
  [SMALL_STATE(66)] = 1364,
  [SMALL_STATE(67)] = 1374,
  [SMALL_STATE(68)] = 1384,
  [SMALL_STATE(69)] = 1394,
  [SMALL_STATE(70)] = 1404,
  [SMALL_STATE(71)] = 1414,
  [SMALL_STATE(72)] = 1424,
  [SMALL_STATE(73)] = 1434,
  [SMALL_STATE(74)] = 1439,
  [SMALL_STATE(75)] = 1444,
  [SMALL_STATE(76)] = 1449,
  [SMALL_STATE(77)] = 1454,
  [SMALL_STATE(78)] = 1459,
  [SMALL_STATE(79)] = 1464,
  [SMALL_STATE(80)] = 1469,
  [SMALL_STATE(81)] = 1474,
  [SMALL_STATE(82)] = 1481,
  [SMALL_STATE(83)] = 1485,
  [SMALL_STATE(84)] = 1489,
  [SMALL_STATE(85)] = 1493,
  [SMALL_STATE(86)] = 1497,
  [SMALL_STATE(87)] = 1501,
  [SMALL_STATE(88)] = 1505,
  [SMALL_STATE(89)] = 1509,
  [SMALL_STATE(90)] = 1513,
  [SMALL_STATE(91)] = 1517,
  [SMALL_STATE(92)] = 1521,
  [SMALL_STATE(93)] = 1525,
  [SMALL_STATE(94)] = 1529,
  [SMALL_STATE(95)] = 1533,
  [SMALL_STATE(96)] = 1537,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ark_operator, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ark_definition, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_type, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ark_definition, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_type, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ark_definition, 5, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_type, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ark_definition_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ark_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_type, 3, 0, 5),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ark_expression, 3, 0, 5),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_type, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_type, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_type, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_expression, 1, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_type, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__number, 2, 0, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 2, 0, 4),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ark_single_string_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ark_single_string_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ark_double_string_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ark_double_string_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_type_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_type_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ark_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_computed_property_name, 5, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ark_property_signature, 3, 0, 6),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__required_property_name, 1, 0, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__required_property_name, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_computed_property_name, 4, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_computed_property_name, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__required_property_name, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_name, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [214] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__optional_property_name, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_arktype(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "arktype",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
